### ISSUE TITLE
Apollo server vs apollo-server-express ?  Latest Version ?

### ISSUE THREAD

**Issue by ammadtahir45** [apollographql/graphql-server-example#3]
Hey Folks!
I need some help regarding your latest release. I've just started with the project setup with apollo and facing some misconception.
Had a look at both of your versions apollo-server and apollo-server-express but unable to identify which one is latest. 
As your docs says that apollo-server is to install for express as it is the latest version. 
![image](https://user-images.githubusercontent.com/40358154/41808696-cfc68024-76fa-11e8-8a9a-d5eb1904b851.png)

But your npm info says that apollo-server is depreciated and good to go with variant name of apollo server.
![image](https://user-images.githubusercontent.com/40358154/41808702-e3dbf576-76fa-11e8-8841-198237ba6c89.png)

Can you please make me clear with this as soon as possible so I can move on.

**Comment by martijnwalraven** [comment]
Apollo Server 2.0 hasn't been quite released yet, so that's why the `apollo-server` package still shows up as deprecated. But you can start out either with `apollo-server@rc` or `apollo-server-express@rc`. The difference is that `apollo-server` is a stand alone server that doesn't allow you to install additional routes or integrate with an existing Express app. So if you need that, you should use `apollo-server-express` instead.

Also, this repository isn't really being maintained (we should probably delete it), so I'm closing this issue. If you have more questions, the best place to ask them is on the #apollo-server channel on [our Slack](https://www.apollographql.com/slack).

**Comment by abernix** [comment]
@martijnwalraven This repository is the example from the [Apollo Server _Getting Started_ guide](https://www.apollographql.com/docs/apollo-server/v2/getting-started.html#More-information) and the source code behind the Glitch.  It should not be deleted — but it should be maintained!
